$script = <<-SCRIPT

apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "workerTwo"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "docker"
  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
  config.vm.provision "shell", inline: $script
end
